// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 14.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，则所做更改将丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace XgxFrameWork.CodeCreaterLayer.T4_Template.T4.DBDAL
{
    using System.Data;
    using System.Data.SqlClient;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\Administrator\Source\Repos\XgxFrameWork\XgxFrameWork.CodeCreaterLayer.T4_Template\T4\DBDAL\SqlServer2005.ttinclude"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class SqlServer2005 : SqlServer2005Base
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 10 "C:\Users\Administrator\Source\Repos\XgxFrameWork\XgxFrameWork.CodeCreaterLayer.T4_Template\T4\DBDAL\SqlServer2005.ttinclude"

public class DbObject : IDbObject
    {
        private string _dbconnectStr;
        private SqlConnection connect;
        private bool isdbosp = false;

        public DbObject()
        {
            this.connect = new SqlConnection();
            this.IsDboSp();
        }

        public DbObject(string DbConnectStr)
        {
            this.connect = new SqlConnection();
            this._dbconnectStr = DbConnectStr;
            this.connect.ConnectionString = DbConnectStr;
        }

        public DbObject(bool SSPI, string Ip, string User, string Pass)
        {
            this.connect = new SqlConnection();
            if (SSPI)
            {
                this._dbconnectStr = "Integrated Security=SSPI;Data Source=" + Ip + ";Initial Catalog=master";
            }
            else if (Pass == "")
            {
                this._dbconnectStr = "user id=" + User + ";initial catalog=master;data source=" + Ip + ";Connect Timeout=30";
            }
            else
            {
                this._dbconnectStr = "user id=" + User + ";password=" + Pass + ";initial catalog=master;data source=" + Ip + ";Connect Timeout=30";
            }
            this.connect.ConnectionString = this._dbconnectStr;
        }

        private SqlCommand BuildQueryCommand(SqlConnection connection, string storedProcName, IDataParameter[] parameters)
        {
            SqlCommand command = new SqlCommand(storedProcName, connection);
            command.CommandType = CommandType.StoredProcedure;
            foreach (SqlParameter parameter in parameters)
            {
                if (parameter != null)
                {
                    if (((parameter.Direction == ParameterDirection.InputOutput) || (parameter.Direction == ParameterDirection.Input)) && (parameter.Value == null))
                    {
                        parameter.Value = DBNull.Value;
                    }
                    command.Parameters.Add(parameter);
                }
            }
            return command;
        }

        public DataTable CreateColumnTable()
        {
            DataTable table = new DataTable();
            DataColumn column = new DataColumn();
            column.DataType = System.Type.GetType("System.String");
            column.ColumnName = "colorder";
            table.Columns.Add(column);
            column = new DataColumn();
            column.DataType = System.Type.GetType("System.String");
            column.ColumnName = "ColumnName";
            table.Columns.Add(column);
            column = new DataColumn();
            column.DataType = System.Type.GetType("System.String");
            column.ColumnName = "TypeName";
            table.Columns.Add(column);
            column = new DataColumn();
            column.DataType = System.Type.GetType("System.String");
            column.ColumnName = "Length";
            table.Columns.Add(column);
            column = new DataColumn();
            column.DataType = System.Type.GetType("System.String");
            column.ColumnName = "Preci";
            table.Columns.Add(column);
            column = new DataColumn();
            column.DataType = System.Type.GetType("System.String");
            column.ColumnName = "Scale";
            table.Columns.Add(column);
            column = new DataColumn();
            column.DataType = System.Type.GetType("System.String");
            column.ColumnName = "IsIdentity";
            table.Columns.Add(column);
            column = new DataColumn();
            column.DataType = System.Type.GetType("System.String");
            column.ColumnName = "isPK";
            table.Columns.Add(column);
            column = new DataColumn();
            column.DataType = System.Type.GetType("System.String");
            column.ColumnName = "cisNull";
            table.Columns.Add(column);
            column = new DataColumn();
            column.DataType = System.Type.GetType("System.String");
            column.ColumnName = "defaultVal";
            table.Columns.Add(column);
            column = new DataColumn();
            column.DataType = System.Type.GetType("System.String");
            column.ColumnName = "deText";
            table.Columns.Add(column);
            return table;
        }

        public bool DeleteTable(string DbName, string TableName)
        {
            try
            {
                SqlCommand command = this.OpenDB(DbName);
                command.CommandText = "DROP TABLE [" + TableName + "]";
                command.ExecuteNonQuery();
                return true;
            }
            catch
            {
                return false;
            }
        }

        public int ExecuteSql(string DbName, string SQLString)
        {
            SqlCommand command = this.OpenDB(DbName);
            command.CommandText = SQLString;
            return command.ExecuteNonQuery();
        }

        public DataTable GetColumnInfoList(string DbName, string TableName)
        {
            if (this.isdbosp)
            {
                return this.GetColumnInfoListSP(DbName, TableName);
            }
            StringBuilder builder = new StringBuilder();
            builder.Append("SELECT distinct * from (select ");
            builder.Append("colorder=C.column_id,");
            builder.Append("ColumnName=C.name,");

            builder.Append("deText=ISNULL(PFD.[value],N''),");
            builder.Append("TypeName=T.name, ");
            builder.Append("Length=C.max_length, ");
            builder.Append("Preci=C.precision, ");
            builder.Append("Scale=C.scale, ");
            builder.Append("IsIdentity=CASE WHEN C.is_identity=1 THEN N'√'ELSE N'' END,");
            builder.Append("isPK=ISNULL(IDX.PrimaryKey,N''),");
            builder.Append("Computed=CASE WHEN C.is_computed=1 THEN N'√'ELSE N'' END, ");
            builder.Append("IndexName=ISNULL(IDX.IndexName,N''), ");
            builder.Append("IndexSort=ISNULL(IDX.Sort,N''), ");
            builder.Append("Create_Date=O.Create_Date, ");
            builder.Append("Modify_Date=O.Modify_date, ");
            builder.Append("cisNull=CASE WHEN C.is_nullable=1 THEN N'√'ELSE N'' END, ");
            builder.Append("defaultVal=ISNULL(D.definition,N'') ");
            
            builder.Append("FROM sys.columns C ");
            builder.Append("INNER JOIN sys.objects O ");
            builder.Append("ON C.[object_id]=O.[object_id] ");
            builder.Append("AND (O.type='U' or O.type='V') ");
            builder.Append("AND O.is_ms_shipped=0 ");
            builder.Append("INNER JOIN sys.types T ");
            builder.Append("ON C.user_type_id=T.user_type_id ");
            builder.Append("LEFT JOIN sys.default_constraints D ");
            builder.Append("ON C.[object_id]=D.parent_object_id ");
            builder.Append("AND C.column_id=D.parent_column_id ");
            builder.Append("AND C.default_object_id=D.[object_id] ");
            builder.Append("LEFT JOIN sys.extended_properties PFD ");
            builder.Append("ON PFD.class=1  ");
            builder.Append("AND C.[object_id]=PFD.major_id  ");
            builder.Append("AND C.column_id=PFD.minor_id ");
            builder.Append("LEFT JOIN sys.extended_properties PTB ");
            builder.Append("ON PTB.class=1 ");
            builder.Append("AND PTB.minor_id=0  ");
            builder.Append("AND C.[object_id]=PTB.major_id ");
            builder.Append("LEFT JOIN ");
            builder.Append("( ");
            builder.Append("SELECT  ");
            builder.Append("IDXC.[object_id], ");
            builder.Append("IDXC.column_id, ");
            builder.Append("Sort=CASE INDEXKEY_PROPERTY(IDXC.[object_id],IDXC.index_id,IDXC.index_column_id,'IsDescending') ");
            builder.Append("WHEN 1 THEN 'DESC' WHEN 0 THEN 'ASC' ELSE '' END, ");
            builder.Append("PrimaryKey=CASE WHEN IDX.is_primary_key=1 THEN N'√'ELSE N'' END, ");
            builder.Append("IndexName=IDX.Name ");
            builder.Append("FROM sys.indexes IDX ");
            builder.Append("INNER JOIN sys.index_columns IDXC ");
            builder.Append("ON IDX.[object_id]=IDXC.[object_id] ");
            builder.Append("AND IDX.index_id=IDXC.index_id ");
            builder.Append("LEFT JOIN sys.key_constraints KC ");
            builder.Append("ON IDX.[object_id]=KC.[parent_object_id] ");
            builder.Append("AND IDX.index_id=KC.unique_index_id ");
            builder.Append("INNER JOIN  ");
            builder.Append("( ");
            builder.Append("SELECT [object_id], Column_id, index_id=MIN(index_id) ");
            builder.Append("FROM sys.index_columns ");
            builder.Append("GROUP BY [object_id], Column_id ");
            builder.Append(") IDXCUQ ");
            builder.Append("ON IDXC.[object_id]=IDXCUQ.[object_id] ");
            builder.Append("AND IDXC.Column_id=IDXCUQ.Column_id ");
            builder.Append("AND IDXC.index_id=IDXCUQ.index_id ");
            builder.Append(") IDX ");
            builder.Append("ON C.[object_id]=IDX.[object_id] ");
            builder.Append("AND C.column_id=IDX.column_id  ");
            builder.Append("WHERE O.name=N'" + TableName + "' ) as t ");
            builder.Append("ORDER BY colorder,ColumnName  ");
            return this.Query(DbName, builder.ToString()).Tables[0];
        }

        public DataTable GetColumnInfoListSP(string DbName, string TableName)
        {
            SqlParameter[] parameters = new SqlParameter[] { new SqlParameter("@table_name", SqlDbType.NVarChar, 0x180), new SqlParameter("@table_owner", SqlDbType.NVarChar, 0x180), new SqlParameter("@table_qualifier", SqlDbType.NVarChar, 0x180), new SqlParameter("@column_name", SqlDbType.VarChar, 100) };
            parameters[0].Value = TableName;
            parameters[1].Value = null;
            parameters[2].Value = null;
            parameters[3].Value = null;
            DataSet set = this.RunProcedure(DbName, "sp_columns", parameters, "ds");
            if (set.Tables.Count <= 0)
            {
                return null;
            }
            DataTable table = set.Tables[0];
            int count = table.Rows.Count;
            DataTable table2 = this.CreateColumnTable();
            for (int i = 0; i < count; i++)
            {
                DataRow row = table2.NewRow();
                row["colorder"] = table.Rows[i]["ORDINAL_POSITION"];
                row["ColumnName"] = table.Rows[i]["COLUMN_NAME"];
                string str = table.Rows[i]["TYPE_NAME"].ToString().Trim();
                row["TypeName"] = (str == "int identity") ? "int" : str;
                row["Length"] = table.Rows[i]["LENGTH"];
                row["Preci"] = table.Rows[i]["PRECISION"];
                row["Scale"] = table.Rows[i]["SCALE"];
                row["IsIdentity"] = (str == "int identity") ? "√" : "";
                row["isPK"] = "";
                row["cisNull"] = (table.Rows[i]["NULLABLE"].ToString().Trim() == "1") ? "√" : "";
                row["defaultVal"] = table.Rows[i]["COLUMN_DEF"];
                row["deText"] = table.Rows[i]["REMARKS"];
                table2.Rows.Add(row);
            }
            return table2;
        }

        public DataTable GetColumnList(string DbName, string TableName)
        {
            try
            {
                if (this.isdbosp)
                {
                    return this.GetColumnListSP(DbName, TableName);
                }
                StringBuilder builder = new StringBuilder();
                builder.Append("Select ");
                builder.Append("a.colorder as colorder,");
                builder.Append("a.name as ColumnName,");
                builder.Append("b.name as TypeName ");
                builder.Append(" from syscolumns a, systypes b, sysobjects c ");
                builder.Append(" where a.xtype = b.xusertype ");
                builder.Append("and a.id = c.id ");
                builder.Append("and c.name ='" + TableName + "'");
                builder.Append(" order by a.colorder");
                return this.Query(DbName, builder.ToString()).Tables[0];
            }
            catch
            {
                return null;
            }
        }

        public DataTable GetColumnListSP(string DbName, string TableName)
        {
            SqlParameter[] parameters = new SqlParameter[] { new SqlParameter("@table_name", SqlDbType.NVarChar, 0x180), new SqlParameter("@table_owner", SqlDbType.NVarChar, 0x180), new SqlParameter("@table_qualifier", SqlDbType.NVarChar, 0x180), new SqlParameter("@column_name", SqlDbType.VarChar, 100) };
            parameters[0].Value = TableName;
            parameters[1].Value = null;
            parameters[2].Value = null;
            parameters[3].Value = null;
            DataSet set = this.RunProcedure(DbName, "sp_columns", parameters, "ds");
            if (set.Tables.Count <= 0)
            {
                return null;
            }
            DataTable table = set.Tables[0];
            int count = table.Rows.Count;
            DataTable table2 = this.CreateColumnTable();
            for (int i = 0; i < count; i++)
            {
                DataRow row = table2.NewRow();
                row["colorder"] = table.Rows[i]["ORDINAL_POSITION"];
                row["ColumnName"] = table.Rows[i]["COLUMN_NAME"];
                string str = table.Rows[i]["TYPE_NAME"].ToString().Trim();
                row["TypeName"] = (str == "int identity") ? "int" : str;
                row["Length"] = table.Rows[i]["LENGTH"];
                row["Preci"] = table.Rows[i]["PRECISION"];
                row["Scale"] = table.Rows[i]["SCALE"];
                row["IsIdentity"] = (str == "int identity") ? "√" : "";
                row["isPK"] = "";
                row["cisNull"] = (table.Rows[i]["NULLABLE"].ToString().Trim() == "1") ? "√" : "";
                row["defaultVal"] = table.Rows[i]["COLUMN_DEF"];
                row["deText"] = table.Rows[i]["REMARKS"];
                table2.Rows.Add(row);
            }
            return table2;
        }

        public DataTable GetDBList()
        {
            string sQLString = "select name,user_name() cuser,'DB' type,crdate dates from sysdatabases";
            return this.Query("master", sQLString).Tables[0];
        }

        public DataTable GetKeyName(string DbName, string TableName)
        {
            DataTable table = this.CreateColumnTable();
            foreach (DataRow row in this.GetColumnInfoList(DbName, TableName).Select(" isPK='√' or IsIdentity='√' "))
            {
                DataRow row2 = table.NewRow();
                row2["colorder"] = row["colorder"];
                row2["ColumnName"] = row["ColumnName"];
                row2["TypeName"] = row["TypeName"];
                row2["Length"] = row["Length"];
                row2["Preci"] = row["Preci"];
                row2["Scale"] = row["Scale"];
                row2["IsIdentity"] = row["IsIdentity"];
                row2["isPK"] = row["isPK"];
                row2["cisNull"] = row["cisNull"];
                row2["defaultVal"] = row["defaultVal"];
                row2["deText"] = row["deText"];
                table.Rows.Add(row2);
            }
            return table;
        }

        public string GetObjectInfo(string DbName, string objName)
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("select b.text ");
            builder.Append("from sysobjects a, syscomments b  ");
            builder.Append("where a.xtype='p' and a.id = b.id  ");
            builder.Append(" and a.name= '" + objName + "'");
            return this.GetSingle(DbName, builder.ToString()).ToString();
        }

        public DataTable GetProcInfo(string DbName)
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("select sysobjects.[name] name,sysusers.name cuser,");
            builder.Append("sysobjects.xtype type,sysobjects.crdate dates ");
            builder.Append("from sysobjects,sysusers ");
            builder.Append("where sysusers.uid=sysobjects.uid ");
            builder.Append("and sysobjects.xtype='P' ");
            builder.Append("order by sysobjects.id");
            return this.Query(DbName, builder.ToString()).Tables[0];
        }

        public DataTable GetProcs(string DbName)
        {
            string sQLString = "select [name] from sysobjects where xtype='P'and [name]<>'dtproperties' order by [name]";
            return this.Query(DbName, sQLString).Tables[0];
        }

        public object GetSingle(string DbName, string SQLString)
        {
            try
            {
                SqlCommand command = this.OpenDB(DbName);
                command.CommandText = SQLString;
                object objA = command.ExecuteScalar();
                if (object.Equals(objA, null) || object.Equals(objA, DBNull.Value))
                {
                    return null;
                }
                return objA;
            }
            catch
            {
                return null;
            }
        }

        public DataTable GetTabData(string DbName, string TableName, int TopNum)
        {
            StringBuilder builder = new StringBuilder();
            string s = "";
            if (TopNum > 0) { s = " top " + TopNum.ToString() + " "; }
            builder.Append("select" + s + " * from [" + TableName + "]");
            return this.Query(DbName, builder.ToString()).Tables[0];
        }

        public DataTable GetTables(string DbName)
        {
            if (this.isdbosp)
            {
                return this.GetTablesSP(DbName);
            }
            string sQLString = "select [name] from sysobjects where xtype='U'and [name]<>'dtproperties' order by [name]";
            return this.Query(DbName, sQLString).Tables[0];
        }

        public DataTable GetTablesInfo(string DbName)
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("select sysobjects.[name] name,sysusers.name cuser,");
            builder.Append("sysobjects.xtype type,sysobjects.crdate dates ");
            builder.Append("from sysobjects,sysusers ");
            builder.Append("where sysusers.uid=sysobjects.uid ");
            builder.Append("and sysobjects.xtype='U' ");
            builder.Append("and  sysobjects.[name]<>'dtproperties' ");
            builder.Append("order by sysobjects.id");
            return this.Query(DbName, builder.ToString()).Tables[0];
        }

        public DataTable GetTablesSP(string DbName)
        {
            SqlParameter[] parameters = new SqlParameter[] { new SqlParameter("@table_name", SqlDbType.NVarChar, 0x180), new SqlParameter("@table_owner", SqlDbType.NVarChar, 0x180), new SqlParameter("@table_qualifier", SqlDbType.NVarChar, 0x180), new SqlParameter("@table_type", SqlDbType.VarChar, 100) };
            parameters[0].Value = null;
            parameters[1].Value = null;
            parameters[2].Value = null;
            parameters[3].Value = "'TABLE'";
            DataSet set = this.RunProcedure(DbName, "sp_tables", parameters, "ds");
            if (set.Tables.Count > 0)
            {
                DataTable table = set.Tables[0];
                table.Columns["TABLE_QUALIFIER"].ColumnName = "db";
                table.Columns["TABLE_OWNER"].ColumnName = "cuser";
                table.Columns["TABLE_NAME"].ColumnName = "name";
                table.Columns["TABLE_TYPE"].ColumnName = "type";
                table.Columns["REMARKS"].ColumnName = "remarks";
                return table;
            }
            return null;
        }

        public DataTable GetTabViews(string DbName)
        {
            if (this.isdbosp)
            {
                return this.GetTabViewsSP(DbName);
            }
            StringBuilder builder = new StringBuilder();
            builder.Append("select [name],sysobjects.xtype type from sysobjects ");
            builder.Append("where (xtype='U' or xtype='V' or xtype='P') ");
            builder.Append("and [name]<>'dtproperties' and [name]<>'syssegments' and [name]<>'sysconstraints' ");
            builder.Append("order by xtype,[name]");
            return this.Query(DbName, builder.ToString()).Tables[0];
        }

        public DataTable GetTabViewsInfo(string DbName)
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("select sysobjects.[name] name,sysusers.name cuser,");
            builder.Append("sysobjects.xtype type,sysobjects.crdate dates ");
            builder.Append("from sysobjects,sysusers ");
            builder.Append("where sysusers.uid=sysobjects.uid ");
            builder.Append("and (sysobjects.xtype='U' or sysobjects.xtype='V' or sysobjects.xtype='P') ");
            builder.Append("and sysobjects.[name]<>'dtproperties' and sysobjects.[name]<>'syssegments' and sysobjects.[name]<>'sysconstraints'  ");
            builder.Append("order by sysobjects.id");
            return this.Query(DbName, builder.ToString()).Tables[0];
        }

        public DataTable GetTabViewsSP(string DbName)
        {
            SqlParameter[] parameters = new SqlParameter[] { new SqlParameter("@table_name", SqlDbType.NVarChar, 0x180), new SqlParameter("@table_owner", SqlDbType.NVarChar, 0x180), new SqlParameter("@table_qualifier", SqlDbType.NVarChar, 0x180), new SqlParameter("@table_type", SqlDbType.VarChar, 100) };
            parameters[0].Value = null;
            parameters[1].Value = null;
            parameters[2].Value = null;
            parameters[3].Value = "'TABLE','VIEW'";
            DataSet set = this.RunProcedure(DbName, "sp_tables", parameters, "ds");
            if (set.Tables.Count > 0)
            {
                DataTable table = set.Tables[0];
                table.Columns["TABLE_QUALIFIER"].ColumnName = "db";
                table.Columns["TABLE_OWNER"].ColumnName = "cuser";
                table.Columns["TABLE_NAME"].ColumnName = "name";
                table.Columns["TABLE_TYPE"].ColumnName = "type";
                table.Columns["REMARKS"].ColumnName = "remarks";
                return table;
            }
            return null;
        }

        public string GetVersion()
        {
            try
            {
                string sQLString = "execute master..sp_msgetversion ";
                return this.Query("master", sQLString).Tables[0].Rows[0][0].ToString();
            }
            catch
            {
                return "";
            }
        }

        public DataTable GetVIEWs(string DbName)
        {
            if (this.isdbosp)
            {
                return this.GetVIEWsSP(DbName);
            }
            string sQLString = "select [name] from sysobjects where xtype='V' and [name]<>'syssegments' and [name]<>'sysconstraints' order by [name]";
            return this.Query(DbName, sQLString).Tables[0];
        }

        public DataTable GetVIEWsInfo(string DbName)
        {
            StringBuilder builder = new StringBuilder();
            builder.Append("select sysobjects.[name] name,sysusers.name cuser,");
            builder.Append("sysobjects.xtype type,sysobjects.crdate dates ");
            builder.Append("from sysobjects,sysusers ");
            builder.Append("where sysusers.uid=sysobjects.uid ");
            builder.Append("and sysobjects.xtype='V' ");
            builder.Append("and sysobjects.[name]<>'syssegments' and sysobjects.[name]<>'sysconstraints'  ");
            builder.Append("order by sysobjects.id");
            return this.Query(DbName, builder.ToString()).Tables[0];
        }

        public DataTable GetVIEWsSP(string DbName)
        {
            SqlParameter[] parameters = new SqlParameter[] { new SqlParameter("@table_name", SqlDbType.NVarChar, 0x180), new SqlParameter("@table_owner", SqlDbType.NVarChar, 0x180), new SqlParameter("@table_qualifier", SqlDbType.NVarChar, 0x180), new SqlParameter("@table_type", SqlDbType.VarChar, 100) };
            parameters[0].Value = null;
            parameters[1].Value = null;
            parameters[2].Value = null;
            parameters[3].Value = "'VIEW'";
            DataSet set = this.RunProcedure(DbName, "sp_tables", parameters, "ds");
            if (set.Tables.Count > 0)
            {
                DataTable table = set.Tables[0];
                table.Columns["TABLE_QUALIFIER"].ColumnName = "db";
                table.Columns["TABLE_OWNER"].ColumnName = "cuser";
                table.Columns["TABLE_NAME"].ColumnName = "name";
                table.Columns["TABLE_TYPE"].ColumnName = "type";
                table.Columns["REMARKS"].ColumnName = "remarks";
                return table;
            }
            return null;
        }

        private bool IsDboSp()
        {           
            return this.isdbosp;
        }

        private SqlCommand OpenDB(string DbName)
        {
            try
            {
                if (this.connect.ConnectionString == "")
                {
                    this.connect.ConnectionString = this._dbconnectStr;
                }
                if (this.connect.ConnectionString != this._dbconnectStr)
                {
                    this.connect.Close();
                    this.connect.ConnectionString = this._dbconnectStr;
                }
                SqlCommand command = new SqlCommand();
                command.Connection = this.connect;
                if (this.connect.State == ConnectionState.Closed)
                {
                    this.connect.Open();
                }
                command.CommandText = "use [" + DbName + "]";
                command.ExecuteNonQuery();
                return command;
            }
            catch (Exception exception)
            {
                string message = exception.Message;
                return null;
            }
        }

        public DataSet Query(string DbName, string SQLString)
        {
            DataSet dataSet = new DataSet();
            try
            {
                this.OpenDB(DbName);
                new SqlDataAdapter(SQLString, this.connect).Fill(dataSet, "ds");
            }
            catch (SqlException exception)
            {
                throw new Exception(exception.Message + "\n" + SQLString);
            }
            return dataSet;
        }

        public bool RenameTable(string DbName, string OldName, string NewName)
        {
            try
            {
                SqlCommand command = this.OpenDB(DbName);
                command.CommandText = "EXEC sp_rename '" + OldName + "', '" + NewName + "'";
                command.ExecuteNonQuery();
                return true;
            }
            catch
            {
                return false;
            }
        }

        public DataSet RunProcedure(string DbName, string storedProcName, IDataParameter[] parameters, string tableName)
        {
            this.OpenDB(DbName);
            DataSet dataSet = new DataSet();
            SqlDataAdapter adapter = new SqlDataAdapter();
            adapter.SelectCommand = this.BuildQueryCommand(this.connect, storedProcName, parameters);
            adapter.Fill(dataSet, tableName);
            return dataSet;
        }

        public string DbConnectStr
        {
            get
            {
                return this._dbconnectStr;
            }
            set
            {
                this._dbconnectStr = value;
            }
        }

        public string DbType
        {
            get
            {
                return "SQL2005";
            }
        }
    }





        
        #line default
        #line hidden
        
        #line 8 "C:\Users\Administrator\Source\Repos\XgxFrameWork\XgxFrameWork.CodeCreaterLayer.T4_Template\T4\DBDAL\Interface.ttinclude"
  


    public interface IDbObject
    {
        /// <summary>
        /// 删除数据表
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <param name="TableName">表名</param>
        /// <returns>删除成功否</returns>
        bool DeleteTable(string DbName, string TableName);
        /// <summary>
        /// 执行SQL语句
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <param name="SQLString">数据表名</param>
        /// <returns>返回影响记录数</returns>
        int ExecuteSql(string DbName, string SQLString);
        /// <summary>
        /// 返回数据表字段列(字段)信息表
        ///  返回表字段结构:
        ///     colorder,ColumnName,TypeName,Length,Preci,Scale,
        ///     IsIdentity('√'),isPK('√'),cisNull('√'),defaultVal,deText
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <param name="TableName">数据表名</param>
        /// <returns>信息表</returns>
        DataTable GetColumnInfoList(string DbName, string TableName);
        /// <summary>
        /// 返回数据列表(简要)
        ///   返回结构:
        ///     colorder,ColumnName,TypeName
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <param name="TableName">数据表名</param>
        /// <returns></returns>
        DataTable GetColumnList(string DbName, string TableName);
        /// <summary>
        /// 返回数据库列表
        ///     返回表结构: name,cuser(所有者),type(对象类型=DB),dates(创建时间)
        /// </summary>
        /// <returns></returns>
        DataTable GetDBList();
        /// <summary>
        /// 返回有标识的主键
        ///   返回表结构:
        ///     colorder,ColumnName,TypeName,Length,Preci,Scale,
        ///     IsIdentity('√'),isPK('√'),cisNull('√'),defaultVal,deText 
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <param name="TableName">数据表名</param>
        /// <returns></returns>
        DataTable GetKeyName(string DbName, string TableName);
        /// <summary>
        /// 返回对象SQL脚本。如存储过程、默认值等
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <param name="objName">对象名</param>
        /// <returns></returns>
        string GetObjectInfo(string DbName, string objName);
        /// <summary>
        /// 返回存储过程列表
        ///   返回表结构：name,cuser(所有人),type(对象类型=P),dates(创建时间)
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <returns></returns>
        DataTable GetProcInfo(string DbName);
        /// <summary>
        /// 返回存储过程名称列表
        ///  返回表结构：name
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <returns></returns>
        DataTable GetProcs(string DbName);
        /// <summary>
        /// 返回一个值
        /// </summary>
        /// <param name="DbName"></param>
        /// <param name="SQLString"></param>
        /// <returns></returns>
        object GetSingle(string DbName, string SQLString);
        /// <summary>
        /// 返回数据表所有(原始)记录
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <param name="TableName">表名</param>
        /// <param name="TopNum">返回前N条记录，为0表示所有</param>
        /// <returns></returns>
        DataTable GetTabData(string DbName, string TableName, int TopNum);
        /// <summary>
        /// 返回所有用户数据表
        ///   返回表结构：name
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <returns></returns>
        DataTable GetTables(string DbName);
        /// <summary>
        /// 返回用户数据表详细信息
        ///   返回表结构：name,cuser(所有者),type(对象类型=U),dates(创建时间)
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <returns></returns>
        DataTable GetTablesInfo(string DbName);
        /// <summary>
        /// 返回数据表、视图、存储过程等对象信息列表
        ///   返回表结构：
        ///    [name],type（对象类型）
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <returns></returns>
        DataTable GetTabViews(string DbName);
        /// <summary>
        /// 返回数据表、视图、存储过程等对象详细信息列表
        ///   返回表结构：
        ///     name,cuser(所有者),type(对象类型),dates(创建时间)
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <returns></returns>
        DataTable GetTabViewsInfo(string DbName);
        /// <summary>
        /// 返回数据服务器版本
        /// </summary>
        /// <returns></returns>
        string GetVersion();
        /// <summary>
        /// 返回数据视图名称列表
        ///    返回表结构：name
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <returns></returns>
        DataTable GetVIEWs(string DbName);
        /// <summary>
        /// 返回数据视图详细列表
        ///   返回表结构：
        ///     name,cuser(所有者),type(对象类型),dates(创建时间)
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <returns></returns>
        DataTable GetVIEWsInfo(string DbName);
        /// <summary>
        /// 返回查询结果
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <param name="SQLString">SQL语句</param>
        /// <returns></returns>
        DataSet Query(string DbName, string SQLString);
        /// <summary>
        /// 重命名对象
        /// </summary>
        /// <param name="DbName">数据库名</param>
        /// <param name="OldName">原名</param>
        /// <param name="NewName">新名</param>
        /// <returns>成功否</returns>
        bool RenameTable(string DbName, string OldName, string NewName);
        /// <summary>
        /// 获取或设置数据连接字符串
        /// </summary>
        string DbConnectStr { get; set; }
        /// <summary>
        /// 获取数据库类型(SQL2000,SQL2005,Oracle,OleDb)
        /// </summary>
        string DbType { get; }
    }



        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class SqlServer2005Base
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
